### ISSUE TITLE
use of info-model parameter names in descriptions

### ISSUE THREAD

**Issue by bhstark2** [mjethanandani/babel-data-model#10]
I noticed the following info-model parameter and object names were used in descriptions. Should these be changed to the corresponding YANG data model names?
babel-neighbors -> list neighbor-objects
babel-route-calculated-metric -> calculated-metric
babel-route-received-metric -> received-metric
     [Since the above 2 are in the metric choice with mandatory=true, does the sentence "Either babel-route-calculated-metric or babel-route-received-metric MUST be provided." even need to be in the YANG descriptions? I'm going to see if we can get a better description for what these 2 parameters are for that would make it clear why it's one or the other.]
babel-route-obj
babel-nbr-stats
babel-information-obj 
babel-metric-comp-algorithms
babel-udp-port
babel-exp-mcast-hello-seqno
babel-exp-ucast-hello-seqno
babel-hmac-algorithms
babel-hmac
babel-hmac-interfaces
babel-hmac-apply-all
babel-interfaces
babel-hmac-key-value
babel-hmac-algorithm
babel-hmac-keys-obj -> hmac-keys list
babel-hmac-obj -> hmac list
babel-dtls-interfaces
babel-dtls-apply-all
babel-dtls-cert-types
babel-dtls-certs -> certs list
babel-cert-private-key -> private-key
babel-dtls-keys-obj -> dtls-keys list
babel-dtls-obj -> dtls list

**Comment by mjethanandani** [comment]
I have been debating that. Here is my dilemma. In every one of the description statements for the attributes, I cite the IM and its section number. If I change the name in the description, it will not match the name or the description in the IM model. By keeping the description, one can see which YANG attribute name matches which IM name.

Besides, YANG is a hierarchical language, and the naming convention calls for child attributes NOT to carry parent name. So babel-hmac-keys-obj becomes hmac-keys because babel is parent and assumed, and it is a list not an obj in YANG.

To the question of:
babel-route-calculated-metric -> calculated-metric
babel-route-received-metric -> received-metric
[Since the above 2 are in the metric choice with mandatory=true, does the sentence "Either babel-route-calculated-metric or babel-route-received-metric MUST be provided." even need to be in the YANG descriptions? I'm going to see if we can get a better description for what these 2 parameters are for that would make it clear why it's one or the other.]

If this is indeed a choice between the two, I need to fix the model by making them a choice.

**Comment by mjethanandani** [comment]
Ignore the last line of my last comment. It is a choice already.

But to your original question, yes, I believe the two descriptions and the fact that it is choice between received-metric and calculated-metric should be provided. I am all for over explaining things, even if they sound redundant.
