### ISSUE TITLE
Stats reset under interface and neighbor

### ISSUE THREAD

**Issue by bhstark2** [mjethanandani/babel-data-model#12]
I see the reset actions are modeled under interfaces and neighbor-objects leafs. Does this mean there is no global reset action that can clear all stats at once, and stats have to be cleared per interface and per neighbor? The info-model reset is where one command clears everything. But if it's easy enough to still clear everything and this is just the way it's done in YANG, then that's fine.

**Comment by mjethanandani** [comment]
Actions in YANG are on the closest parent to the action. That is why you see them where you see them, under container stats. I cannot put a global action command, because it would mean I am trying to reset container babel??

So if someone wants to clear stats, they would have to do reset under interface and neighbor-obj. Kind of a pain, but as you said, that is the way it is done in YANG.

**Comment by bhstark2** [comment]
OK
