### ISSUE TITLE
Default link properties

### ISSUE THREAD

**Issue by mjethanandani** [mjethanandani/babel-data-model#17]
Can the data model define a default link property. For example, can the default link property be "wired", assuming of course that most instances of babel will be over a wired link. 

This does not prevent the link property from being changed. It is just another attribute that will not need assignment if the default value works in most scenarios.

**Comment by bhstark2** [comment]
I'm trying to understand how this works and what it means (without going and reading the YANG spec) in the context of the babel-interfaces object and its parameters. Since we've agreed that the object is read-only, the management system won't be creating new instances. And I thought you said specifying YANG DM defaults wasn't useful in constraining the application when the application was auto-creating new instances. In this case, I'm not sure it's a good idea to try to constrain the decision logic an application goes through in assigning link properties to a new interface.
If parameters within an existing instance are being updated, my expectation is that any parameter not explicitly included in the update will not be updated (and will not be changed to a default value); it will retain its existing value. If a parameter is included in the update but with an invalid value (e.g., link-property included with null value or not-in-the-list value), I would expect this to be an error, and would not expect the current value to be changed to a default value as a result.
So what is the impact of or need for a default value in the context of read-only objects?
For the babel-constants, the defaults really are there for the sake of the babel implementers. And they're very well-known and well-defined constant defaults. Other than those, I really think the only objects whose parameters might need defaults are objects that can be written.

**Comment by mjethanandani** [comment]
There is no default link property. Instead, implementations will determine if they can infer the type of link from its name or other parameters and assign their own default values.
